# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: 程序员uncle
#author:
#  name: Guoqing
#  email: guoqing.jia@qq.com

description: >- # this means to ignore newlines until "baseurl:"
  公众号「程序员uncle/brother」已接入 ChatGPT。
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://cxyds.top" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
remote_theme: "mmistakes/minimal-mistakes@master"
plugins:
  - jekyll-include-cache

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

include:
  - _pages

locale: zh-CN
title_separator: "|"
show_excerpts: true
timezone: Asia/Shanghai
minimal_mistakes_skin: "dirt"
search: true
author:
  name     : "程序员uncle"
  avatar   : "/assets/bio-photo.ico"
  bio      : "人生苦短，及时行乐"
  links:
    - label: "邮箱"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:jia.guoqing@qq.com"
    - label: "微信"
      icon: "fab fa-weixin"
      url: "/2023/09/17/writer-qr.html"
defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      related: true
      toc: true
      toc_label: 目录
      toc_sticky: true
